### ISSUE TITLE
IDEA: ASDOT notation

### ISSUE THREAD

**Issue by mzbroch** [nautobot/nautobot-app-bgp-models#29]
### Environment
* Nautobot version: 1.5.0
* nautobot-bgp-models version:  0.7.1

### Proposed Functionality
 **32-bit ASN notations.** Nautobot should be able to read and convert ASN between AS plain and AS dot notations.  

### Use Case
This enables human readable ASNs.

**Comment by cmacnevin** [comment]
Any large scale modern layer 3 data center relies on 4-byte ASNs, which are most often represented using asdot notation. Definitely agree this is a necessity.

**Comment by mzbroch** [comment]
> Any large scale modern layer 3 data center relies on 4-byte ASNs, which are most often represented using asdot notation. Definitely agree this is a necessity.

For the database field type it will remain integer (asplain), we have to explore how this could be implemented in a way to keep the consistency (how to support BigIntegerField (asplain) vs Char (asdot+))

**Comment by rifen** [comment]
Ran into this this week! 👍🏻 Would be a great addition.

**Comment by mzbroch** [comment]
@mattmiller87  @glennmatthews 

We could solve this by adding two new fields on the ASN model: `as_dot` and `as_dot_plus` that would be computed and checked in the model's `clean()` method. This should provide sufficient type consistency for UI / API displaying and filtering.

**Comment by glennmatthews** [comment]
Do these even need to be database fields or can they just be computed `@property` items?

**Comment by mzbroch** [comment]
> Do these even need to be database fields or can they just be computed `@property` items?

This could work too, I was concerned with filtering of computed data but this might not be an issue

**Comment by cmacnevin** [comment]
Re @mzbroch 's comment above, here's something to consider:

This isn't a request in the original ask, but it would be awesome if we could actually plan ASNs with their own view, the same way we do with prefixes. Enabling asdot notation would mean this can be hierarchical - or at least a simple two-level hierarchy - which would actually be very useful when planning data center routing space.

So what Im suggesting here is that if it's a computed field, does that make it easier or harder to do something like this?

**Comment by mzbroch** [comment]
> This isn't a request in the original ask, but it would be awesome if we could actually plan ASNs with their own view, the same way we do with prefixes. Enabling asdot notation would mean this can be hierarchical - or at least a simple two-level hierarchy - which would actually be very useful when planning data center routing space.

As in the #205 , ASN ASDOT will be shown in the list view of ASNs , allowing for sorting as well. Although not hierarchical, this should be very similar user experience to the described above.
