### ISSUE TITLE
Cut a 1.0 release

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot-app-bgp-models#83]
Given this app already has adoption, it should at least have a 1.0 release.

Requires: 
- #25 
- #26 
- #135

**Comment by retnuh** [comment]
Agreed, we're looking to migrate to this from the pre-release version, and not having a tagged release makes that pretty awkward.

**Comment by mzbroch** [comment]
Release 1.0 and 2.0 has been announced recently. Please refer to relevant release notes.
